name: Windows - RustDesk

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360  # 6 horas por job
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
      
      - name: Download Previous State
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: state
          path: ./state

      - name: Ensure State Directory Exists
        run: mkdir state || true

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py

      - name: Save State
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: state
          path: ./state
